/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registroxd;



import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import registroxd.Login;
import registroxd.Registro;

import javax.swing.JOptionPane;

    
/**
 *
 * @author Luigy Miranda
 */
public class Vent extends javax.swing.JFrame {
DefaultTableModel Model=new DefaultTableModel();
Registro res=null;
    /**
     * Creates new form Vent
     */

    public Vent() {
        
        initComponents();
        Model.addColumn("Cantidad");
        Model.addColumn("  Detalle  ");
        Model.addColumn("Monto - Precio Final");
        Model.addColumn("Digitalizacion");
        Hora.setText(fechas());    
        Vent.tabla1.setModel(Model);
        
        cbn.setSelected(false);
        ccolor.setSelected(false);
        ibn.setSelected(false);
        icolor.setSelected(false);
                       if (Login.usuario.getText().equalsIgnoreCase("juliana")) {
           this.registrox.setEnabled(true);
            
                } else {
        }




    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbn = new javax.swing.JCheckBox();
        ccolor = new javax.swing.JCheckBox();
        ibn = new javax.swing.JCheckBox();
        icolor = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        defectmonto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        can = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        deta = new javax.swing.JTextField();
        mon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        registrox = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Registro de ventas.");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbn.setText("Copia B/N");
        cbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbnMouseReleased(evt);
            }
        });

        ccolor.setText("Copia Color");
        ccolor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ccolorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ccolorMouseReleased(evt);
            }
        });

        ibn.setText("Impresiones a B/N");
        ibn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ibnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ibnMouseReleased(evt);
            }
        });

        icolor.setText("Impresiones a Color");
        icolor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icolorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                icolorMouseReleased(evt);
            }
        });

        jLabel6.setText("Monto por defecto :");

        defectmonto.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ccolor)
                    .addComponent(cbn))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ibn)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(defectmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(icolor))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbn)
                    .addComponent(ibn)
                    .addComponent(jLabel6)
                    .addComponent(defectmonto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccolor)
                    .addComponent(icolor))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cantidad", "Detalle", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla1);

        jLabel2.setText("Cantidad");

        jLabel3.setText("Detalle");

        jLabel4.setText("Monto");

        Hora.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        Hora.setText("dd/MM/YYYY");

        registrox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ver registro.png"))); // NOI18N
        registrox.setBorder(null);
        registrox.setBorderPainted(false);
        registrox.setContentAreaFilled(false);
        registrox.setEnabled(false);
        registrox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroxActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cerrar Sesion.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guardar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Clic aqui para ver los registro del dia de hoy!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deta, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(can, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(registrox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(can, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(deta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(registrox, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
        String CobroCopia="0.05";
        String CobroCopiaC="0.25";
        String CobroI="0.10";
        String CobroIC="0.25";
        Integer Valor4;
        Integer Valor3;
        Integer Valor2;
        Integer Valor1;

    double total=0.00;

    
    public void Calculos(){
        
    }    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login lop=new Login();
        lop.setVisible(true);
        lop.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        double cantide = Double.parseDouble(Vent.can.getText());
        double precd = Double.parseDouble(Vent.mon.getText());
        double cbnf= Double.parseDouble(CobroCopia);
        double cc= Double.parseDouble(CobroCopiaC);
        double im= Double.parseDouble(CobroI);
        double imc= Double.parseDouble(CobroIC);
        total= cantide * precd;
        String []agregar=new String[4];
        agregar[0]=Vent.can.getText();
        agregar[1]=Vent.deta.getText();
        agregar[2]="$ "+this.total;  
        if (cbn.isSelected()) {
        agregar[3]= Vent.cbn.getText();
        } else if (ccolor.isSelected()) {
        agregar[3] = Vent.ccolor.getText();
        } else if (ibn.isSelected()) {
        agregar[3] = Vent.ibn.getText();
        } else if (icolor.isSelected()) {
        agregar[3] = Vent.icolor.getText();
  
        }
        Model.addRow(agregar);
        Vent.can.setText("");
        Vent.deta.setText("");
        Vent.mon.setText("");
        Vent.defectmonto.setText(" ");
        

        


        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbnMousePressed
        // TODO add your handling code here:
        /////copia a b/n presionado
         Vent.defectmonto.setText(CobroCopia);

         Vent.mon.setText(CobroCopia);
        
        
    }//GEN-LAST:event_cbnMousePressed

    private void ccolorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ccolorMousePressed
        // TODO add your handling code here:
        
        ////Copia color presionado
              Vent.defectmonto.setText(CobroCopiaC);
              Vent.mon.setText(CobroCopiaC);
    }//GEN-LAST:event_ccolorMousePressed

    private void ibnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ibnMousePressed
        // TODO add your handling code here:
        ////impresiones /nb
           Vent.defectmonto.setText(CobroI);
        Vent.mon.setText(CobroI);
    }//GEN-LAST:event_ibnMousePressed

    private void icolorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icolorMousePressed
        // TODO add your handling code here:
        ////impresiones color
              Vent.defectmonto.setText(CobroIC);
              Vent.mon.setText(CobroIC);
    }//GEN-LAST:event_icolorMousePressed

    private void registroxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroxActionPerformed
        // TODO add your handling code here:
        Registro ret=new Registro();
        

    }//GEN-LAST:event_registroxActionPerformed

    private void cbnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbnMouseReleased
        // TODO add your handling code here:
     
    }//GEN-LAST:event_cbnMouseReleased

    private void ccolorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ccolorMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ccolorMouseReleased

    private void ibnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ibnMouseReleased
       // TODO add your handling code here:
   
    }//GEN-LAST:event_ibnMouseReleased

    private void icolorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icolorMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_icolorMouseReleased


    
        public static String fechas(){
        Date dat=new Date();
        SimpleDateFormat formatofecha=new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(dat);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Hora;
    public static javax.swing.JTextField can;
    public static javax.swing.JCheckBox cbn;
    public static javax.swing.JCheckBox ccolor;
    public static javax.swing.JLabel defectmonto;
    public static javax.swing.JTextField deta;
    public static javax.swing.JCheckBox ibn;
    public static javax.swing.JCheckBox icolor;
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField mon;
    private javax.swing.JButton registrox;
    public static javax.swing.JTable tabla1;
    // End of variables declaration//GEN-END:variables
}
